// COURSE: CSCI1620
// TERM: Spring 2018
//
// NAME: Dr. Dorn
// RESOURCES: No external resources were use in writing this file.

package scraper.base;
import scraper.application.ScraperWindow;

/**
 * This class provides a main entry point for the 
 * WebScraper's GUI code. 
 * 
 * @author bdorn
 *
 */
public class ScraperMain
{
	////////////////////////////////////////////////
	//WARNING:
	//DO NOT EDIT THIS FILE OR THE GUI MAY NOT OPEN
	////////////////////////////////////////////////
	
	/**
	 * Loads and starts the GUI application.
	 * @param args 	Command line arguments, not used.
	 */
	public static void main(String[] args)
	{	
		ScraperWindow.start();
	}
}
